trigger:
  batch: true
  branches:
    include:
      - infrastructureIntegration

resources:
  - repo: self

parameters:
  - name: imageTag
    type: string
    default: '1.0.0'

variables:
  - group: 'BuildParameters'

stages:
  - stage: CheckRunningPackages
    displayName: Check Running Packages
    jobs:
      - job: CheckRunningPackages
        displayName: Check Running Packages
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            displayName: Check Running Packages
            inputs:
              targetType: 'inline'
              script: |
                sudo apt update
                sudo apt openjdk-21-jdk -y
                $env:JAVA_HOME = "/usr/lib/jvm/java-1.21.0-openjdk-amd64"
                $env:PATH = "$env:JAVA_HOME/bin;$env:PATH"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                executeCommand -command "helm version"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                executeCommand -command "java --version"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                executeCommand -command "mvn -v"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                executeCommand -command "npm version"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                executeCommand -command "minikube version"
                $minikubeStatus = (minikube status 2>$null).Trim()
                if ($minikubeStatus -contains "host: Stopped") {
                  . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                  executeCommand -command "minikube start"
                } else {
                  Write-Host "Minikube already started"
                }
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                controlContext -requested "minikube"
  - stage: CleanPreviousInstall
    displayName: Clean Previous Install
    jobs:
      - job: CleanPreviousInstall
        displayName: Clean Previous Install
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            displayName: Clean Previous Install
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "**** Cleaning old builds with Helm and Docker ****"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                cleanLocalInfrastructures
                Write-Host "**** Docker Images Pruned ****"
  - stage: HelmInstall
    displayName: Helm Install
    jobs:
      - job: HelmInstall
        displayName: Helm Install
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            displayName: Helm Install
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "**** Creating Three Helm Manifests Empty. It will start in a minute. ****"
                Start-Sleep -Seconds 60
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                createHelmManifest -microservice "usersubscription"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                createHelmManifest -microservice "videogameproducts"
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                createHelmManifest -microservice "videogamestore"
  - stage: Build_and_Push_On_Docker
    displayName: 'Build And Push On Docker'
    jobs:
      - job: Build_and_Push_On_Docker
        displayName: 'Build and Push on Docker'
        pool:
          name: Default
        steps:
          - script: |
              print("*** Pipeline Deploy in Local is in Running. This Pipeline will continue after finished. ***")
              from azure.devops.connection import Connection
              from msrest.authentication import BasicAuthentication
              personal_access_token = "$(authentication)"
              organization_url = "https://dev.azure.com/infraplayground"
              credentials = BasicAuthentication('', personal_access_token)
              connection = Connection(base_url=organization_url, creds=credentials)
              pipeline_client = connection.clients.get_build_client()
              project_name = "videogame-store-example-infrastructure"
              pipeline_id = "3"
              build = pipeline_client.queue_build(project=project_name, definition_id=int(pipeline_id))
            displayName: 'Build/Deploy Pipeline'
  - stage: Replace_Images_Deployment
    displayName: 'Replace Images Deployment'
    jobs:
      - job: Replace_Images_Deployment
        displayName: 'Replace Images Deployment'
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            displayName: 'Deploy Local Pipeline'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host *** Pipeline Deploy in Local is in Running. This Pipeline will continue after finished. ****
                $pat = "$(authentication)"
                $parameters = @{
                      imageName = "usersubscription"
                      imageVersion = "${{ parameters.imageTag }}"
                      deployAll = true
                }
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                runPipeline -pipelineId "4" -pat $pat -parameters $parameters
  - stage: Test_Automation
    displayName: 'Test Automation'
    jobs:
      - job: Test_Automation
        displayName: 'Test Automation'
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            displayName: 'Automation Pipeline'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "*** Pipeline Automation Test is in Running. This Pipeline will continue after finished. ***"
                $pat = "$(authentication)"
                $parameters = @{
                      USERSUBSCRIPTION_TEST = true
                      VIDEOGAMEPRODUCTS_TEST = true
                      VIDEOGAMESTORE_TEST = true
                }
                . "$(Build.SourcesDirectory)/powershell-scripts/infrastructureService.ps1"
                runPipeline -pipelineId "7" -pat $pat -parameters $parameters
  - stage: Cleanup
    displayName: Cleanup Stage
    dependsOn: Test_Automation
    condition: always()
    jobs:
      - job: CleanupJob
        displayName: Cleanup Job
        pool:
          name: Default
        steps:
          - script: |
              if [ "$(isPullRequest)" = true ]; then
                  echo "Pipeline Success"
                  docker image ls | grep usersubscription
                  docker image ls | grep videogameproducts
                  docker image ls | grep videogamestore
                  helm list --short -n usersubscription
                  helm list --short -n videogameproducts
                  helm list --short -n videogamestore
              else
                  echo "Pipeline Failure"
              fi
            displayName: 'Print Pipeline Status'
          - task: DeleteFiles@1
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: '**'