trigger:
  batch: true
  branches:
    include:
      - master

resources:
  - repo: self

variables:
  - group: Build Parameters
  - name: username_dockerhub
    value: $[variables['Build Parameters.params.username_dockerhub']]
  - name: password_dockerhub
    value: $[variables['Build Parameters.params.password_dockerhub']]


parameters:
  - name: imageTag
    type: string
    default: 'latest'

stages:
  - stage: Maven_Stage
    displayName: Maven Stage
    jobs:
      - job: Maven_Stage
        displayName: Maven Stage
        pool:
          name: Default
        steps:
          - task: Bash@3
            displayName: 'Change script permissions'
            inputs:
              targetType: 'inline'
              script: |
                chmod +x $(Build.SourcesDirectory)/linux-scripts/buildService.sh
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sudo ./linux-scripts/buildService.sh create_jar_file "$(Build.SourcesDirectory)/store-usersubscription-example"
                sudo ./linux-scripts/buildService.sh create_jar_file "$(Build.SourcesDirectory)/store-videogame-products-example"
                sudo ./linux-scripts/buildService.sh create_jar_file "$(Build.SourcesDirectory)/store-videogamestore-final-example"
            displayName: 'Build Maven Stage'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-usersubscription-example/target/usersubscription.jar'
              artifact: 'usersubscription.jar'
            displayName: 'Publish Artifact UserSubscription'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogame-products-example/target/videogamestore.jar'
              artifact: 'videogamestore.jar'
            displayName: 'Publish Artifact VideogameProducts'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogamestore-final-example/target/videogamestorefinal.jar'
              artifact: 'videogamestorefinal.jar'
            displayName: 'Publish Artifact VideogameStore'
  - stage: Build_and_Push_Stage
    displayName: Docker Stage
    jobs:
      - job: Build
        displayName: Docker Stage
        pool:
          name: Default
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'usersubscription.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-usersubscription-example/target'
            displayName: 'Download Artifact UserSubscription'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'videogamestore.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-videogame-products-example/target'
            displayName: 'Download Artifact VideogameProducts'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'videogamestorefinal.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-videogamestore-final-example/target'
            displayName: 'Download Artifact VideogameStore'
          - task: Bash@3
            displayName: 'Docker Build and Push'
            inputs:
              targetType: 'inline'
              script: |
                sudo chmod 777 linux-scripts/buildService.sh
                generatedPassword=$(shut -i 0-999999 -n 1 | printf "%06d\n" $(cat))
                sudo ./linux-scripts/buildService.sh use_ansible_vault "${generatedPassword}" "encrypt" "${{ parameters.imageTag }}"
                sudo ./linux-scripts/buildService.sh build_and_push_on_docker "$(Build.SourcesDirectory)/store-usersubscription-example" "usersubscription" "${{ parameters.imageTag }}" "${generatedPassword}" "${{ variables.username_dockerhub }}" "${{ variables.password_dockerhub }}"
                sudo ./linux-scripts/buildService.sh build_and_push_on_docker "$(Build.SourcesDirectory)/store-videogame-products-example" "videogameproducts" "${{ parameters.imageTag }}" "${generatedPassword}" "${{ variables.username_dockerhub }}" "${{ variables.password_dockerhub }}"
                sudo ./linux-scripts/buildService.sh build_and_push_on_docker "$(Build.SourcesDirectory)/store-videogamestore-final-example" "videogamestore" "${{ parameters.imageTag }}" "${generatedPassword}" "${{ variables.username_dockerhub }}" "${{ variables.password_dockerhub }}"
                sudo ./linux-scripts/buildService.sh use_ansible_vault "${generatedPassword}" "decrypt"
          - task: Docker@2
            inputs:
              command: 'logout'
            displayName: 'Docker Logout'
  - stage: Cleanup
    displayName: Cleanup Stage
    dependsOn: Build_And_Push_Stage
    condition: always()
    jobs:
      - job: CleanupJob
        displayName: Cleanup Job
        pool:
          name: Default
        steps:
          - script: |
              if [ "$(isPullRequest)" = true ]; then
                  echo "Pipeline Success"
              else
                  echo "Pipeline Failure"
              fi
            displayName: 'Print Pipeline Status'
          - task: DeleteFiles@1
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: '**'




