trigger:
  batch: true
  branches:
    include:
      - master

resources:
  - repo: self

parameters:
  - name: imageTag
    type: string
    default: 'latest'

stages:
  - stage: Maven_Stage
    displayName: Maven Stage
    jobs:
      - job: Maven_Stage
        displayName: Maven Stage
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-usersubscription-example"
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-videogame-products-example"
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-videogamestore-final-example"
            displayName: 'Build Maven Stage'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-usersubscription-example/target/usersubscription.jar'
              artifact: 'usersubscription.jar'
            displayName: 'Publish Artifact'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogame-products-example/target/videogamestore.jar'
              artifact: 'videogamestore.jar'
            displayName: 'Publish Artifact'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogamestore-final-example/target/videogamestorefinal.jar'
              artifact: 'videogamestorefinal.jar'
            displayName: 'Publish Artifact'
  - stage: Build_and_Push_Stage
    displayName: Docker Stage
    jobs:
      - job: Build
        displayName: Docker Stage
        pool:
          name: Default
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifacts'
            inputs:
              buildType: 'current'
              downloadPath: '$(Build.SourcesDirectory)'
              itemPattern: |
                **/store-usersubscription-example/target/usersubscription.jar
                **/store-videogame-products-example/target/videogamestore.jar
                **/store-videogamestore-final-example/target/videogamestorefinal.jar'
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'
              displayName: 'Docker Login'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-usersubscription-example" -ImageName "usersubscription" -ImageTag ${{ parameters.imageTag }}
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-videogame-products-example" -ImageName "videogameproducts" -ImageTag ${{ parameters.imageTag }}            
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-videogamestore-final-example" -ImageName "videogamestore" -ImageTag ${{ parameters.imageTag }}
            displayName: 'Build and Push Stage'
          - task: Docker@2
            inputs:
              command: 'logout'
post:
  success:
    steps:
      - script: |
          echo "Pipeline Success"
        displayName: 'Print Success Message'
  failure:
    steps:
      - script: |
          echo "Pipeline Failure"
        displayName: 'Print Failure Message'


