trigger:
  batch: true
  branches:
    include:
      - master

resources:
  - repo: self

parameters:
  - name: imageTag
    type: string
    default: 'latest'

stages:
  - stage: Maven_Stage
    displayName: Maven Stage
    jobs:
      - job: Maven_Stage
        displayName: Maven Stage
        pool:
          name: Default
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-usersubscription-example"
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-videogame-products-example"
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                createJarFile -Path "$(Build.SourcesDirectory)/store-videogamestore-final-example"
            displayName: 'Build Maven Stage'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-usersubscription-example/target/usersubscription.jar'
              artifact: 'usersubscription.jar'
            displayName: 'Publish Artifact UserSubscription'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogame-products-example/target/videogamestore.jar'
              artifact: 'videogamestore.jar'
            displayName: 'Publish Artifact VideogameProducts'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/store-videogamestore-final-example/target/videogamestorefinal.jar'
              artifact: 'videogamestorefinal.jar'
            displayName: 'Publish Artifact VideogameStore'
  - stage: Build_and_Push_Stage
    displayName: Docker Stage
    jobs:
      - job: Build
        displayName: Docker Stage
        pool:
          name: Default
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'usersubscription.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-usersubscription-example/target'
            displayName: 'Download Artifact UserSubscription'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'videogamestore.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-videogame-products-example/target'
            displayName: 'Download Artifact VideogameProducts'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'videogamestorefinal.jar'
              downloadPath: '$(Build.SourcesDirectory)/store-videogamestore-final-example/target'
            displayName: 'Download Artifact VideogameStore'
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              command: 'login'
            displayName: 'Docker Login'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-usersubscription-example" -ImageName "usersubscription" -ImageTag ${{ parameters.imageTag }}
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-videogame-products-example" -ImageName "videogameproducts" -ImageTag ${{ parameters.imageTag }}            
                . "$(Build.SourcesDirectory)/powershell-scripts/buildService.ps1"
                buildAndPushOnDocker -Path "$(Build.SourcesDirectory)/store-videogamestore-final-example" -ImageName "videogamestore" -ImageTag ${{ parameters.imageTag }}
            displayName: 'Build and Push Stage'
          - task: Docker@2
            inputs:
              command: 'logout'
            displayName: 'Docker Logout'
  - stage: Cleanup
    displayName: Cleanup Stage
    dependsOn: Build_And_Push_Stage
    condition: always()
    jobs:
      - job: CleanupJob
        displayName: Cleanup Job
        pool:
          name: Default
        steps:
          - script: |
              if [ "$(isPullRequest)" = true ]; then
                  echo "Pipeline Success"
              else
                  echo "Pipeline Failure"
              fi
            displayName: 'Print Pipeline Status'
          - task: DeleteFiles@1
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: '**'




